server:
  port: 8000
  servlet:
    context-path: /content
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mlb-content?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0
    host: 192.168.56.102
    port: 6379