server:
  port: 8080
  servlet:
    context-path: /

client:
  sources:
    - host: 127.0.0.1
      port: 3306
      schema: mlb-content
      username: root
      password: 123456

spring:
  rabbitmq:
    host: 192.168.56.102
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    listener:
      simple:
        concurrency: 5 # 消费端最小并发数
        max-concurrency: 10 # 消费端最大并发数
        prefetch: 5 # 一次请求中预处理的消息数量

### 自定义配置
message:
  rabbitmq:
    binlog-sync-exchange: binlog-sync-exchange
    binlog-sync-queue: binlog-sync-queue
    binlog-sync-routing-key: binlog-sync-routing-key